"""
Stage 3 (ETF Count) — label-noise sensitivity / robustness analysis.

Companion to label_noise_sweep_stage1.py. Same principle: treat the label-noise
level as the INDEPENDENT variable and measure how learnability (R^2) depends on
it, instead of tuning the noise to a target R^2.

Design:
  - total_etfs is generated by get_num_etfs() — a DETERMINISTIC function of
    portfolio capital + risk profile + experience, plus a ±1 jitter applied to
    each sleeve with probability ETF_COUNT_NOISE_P.
  - We sweep ETF_COUNT_NOISE_P from 0 (fully deterministic) to 1 (every sleeve
    jittered) and also report a MODEL-FREE noise measure: the mean absolute
    deviation (in ETFs) between the noisy count and the deterministic count.
  - Model (RandomForestRegressor) and train/test split HELD FIXED across points.
  - Risk profile is fixed to the stable argmax label so only the ETF-count noise
    varies (not the Stage-1 label noise).

Output: table + plot (R^2 & MAE vs injected noise) saved to evaluation_reports/.

    python notebooks/label_noise_sweep_stage3.py
"""
import os
import sys
import glob
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
import src.allocations as alloc  # noqa: E402
from src.allocations import get_profile_probabilities, get_num_etfs  # noqa: E402

CLASSES = ['Aggressive', 'Moderate', 'Conservative']
SLEEVES = ['Equity', 'Bond', 'Alternative']
OUT_DIR = os.path.join(ROOT, 'evaluation_reports')

# --- 1. Load raw investors -----------------------------------------------------
inv_file = sorted(glob.glob(os.path.join(ROOT, 'data', 'processed',
                                          'synthetic_investor_data_*.csv')))[-1]
inv = pd.read_csv(inv_file).rename(columns={
    'Age': 'age', 'InvestmentHorizon': 'horizon', 'RiskTolerance': 'risk_tolerance',
    'Income': 'income', 'ExperienceYears': 'experience',
})
print(f'Investors: {len(inv)} from {os.path.basename(inv_file)}')

# --- 2. Stable risk profile (argmax) so only ETF-count noise varies ------------
prob_dicts = inv.apply(get_profile_probabilities, axis=1)
P = np.array([[d[c] for c in CLASSES] for d in prob_dicts])
profile = np.array(CLASSES)[P.argmax(axis=1)]
capital = inv['InvestmentCapital'].values
experience = inv['experience'].values

# --- 3. Features (same engineering as prepare_data.py) -------------------------
feature_columns = ['age', 'Gender', 'Education', 'MaritalStatus', 'HouseholdSize',
                   'income', 'InvestmentGoal', 'horizon', 'InvestmentCapital',
                   'risk_tolerance', 'FinancialInvolvement', 'experience']
categorical = ['Gender', 'Education', 'MaritalStatus', 'InvestmentGoal',
               'risk_tolerance', 'FinancialInvolvement']
numerical = ['age', 'HouseholdSize', 'income', 'horizon', 'InvestmentCapital', 'experience']
X = inv[feature_columns].copy()

idx = np.arange(len(inv))
tr_idx, te_idx = train_test_split(idx, test_size=0.2, random_state=42, stratify=profile)
pre = ColumnTransformer([
    ('num', StandardScaler(), numerical),
    ('cat', OneHotEncoder(drop='first', sparse_output=False), categorical),
])
X_tr = pre.fit_transform(X.iloc[tr_idx])
X_te = pre.transform(X.iloc[te_idx])


def make_totals(noise_p):
    """Generate total_etfs for every investor at a given noise level."""
    alloc.ETF_COUNT_NOISE_P = noise_p             # rebinds the module global
    alloc._etf_rng = np.random.default_rng(123)   # reset for reproducibility
    totals = np.array([
        sum(get_num_etfs(s, profile[i], capital[i], experience[i]) for s in SLEEVES)
        for i in range(len(inv))
    ])
    return totals


# Deterministic baseline (noise_p = 0) — reference for model-free noise measure
det_totals = make_totals(0.0)

# --- 4. Sweep the noise level --------------------------------------------------
NOISE = [0.0, 0.1, 0.2, 0.25, 0.4, 0.6, 0.8, 1.0]
rows = []
print(f"\n{'noise_p':>8} {'meanΔ':>6} {'train_R2':>9} {'test_R2':>8} {'MAE':>6} {'exact':>6}")
for p in NOISE:
    y = make_totals(p)
    inj = float(np.mean(np.abs(y - det_totals)))    # model-free: avg ETFs perturbed
    y_tr, y_te = y[tr_idx], y[te_idx]

    reg = RandomForestRegressor(n_estimators=200, max_depth=5,
                                random_state=42, n_jobs=-1)
    reg.fit(X_tr, y_tr)
    train_r2 = r2_score(y_tr, reg.predict(X_tr))
    pred = reg.predict(X_te)
    test_r2 = r2_score(y_te, pred)
    mae = mean_absolute_error(y_te, pred)
    exact = float(np.mean(np.round(pred) == y_te))
    rows.append({'ETF_COUNT_NOISE_P': p, 'mean_abs_perturb': inj,
                 'train_r2': train_r2, 'test_r2': test_r2, 'mae': mae,
                 'exact_match': exact})
    print(f"{p:>8.2f} {inj:>6.2f} {train_r2:>9.3f} {test_r2:>8.3f} {mae:>6.3f} {exact:>6.3f}")

df = pd.DataFrame(rows)
csv_path = os.path.join(OUT_DIR, 'stage3_label_noise_sweep.csv')
df.to_csv(csv_path, index=False)
print(f"\nSaved table -> {csv_path}")

# --- 5. Plot R^2 (and MAE) vs the noise knob -----------------------------------
fig, ax1 = plt.subplots(figsize=(9, 5.5))
ax1.plot(df['ETF_COUNT_NOISE_P'], df['train_r2'], 'o-', color='coral', label='Train R²')
ax1.plot(df['ETF_COUNT_NOISE_P'], df['test_r2'], 'o-', color='steelblue', label='Test R²')
ax1.set_xlabel('ETF_COUNT_NOISE_P  (probability each sleeve gets a ±1 jitter)')
ax1.set_ylabel('R²')
ax1.set_ylim(0, 1.02)
ax1.set_title('Stage 3: ETF-count learnability vs injected label noise\n'
              '(model & split held fixed; only ETF-count noise varies)')
for _, r in df.iterrows():
    ax1.annotate(f"{r['mean_abs_perturb']:.2f}", (r['ETF_COUNT_NOISE_P'], r['test_r2']),
                 textcoords='offset points', xytext=(0, -14), fontsize=7,
                 ha='center', color='steelblue')
ax1.legend(loc='upper right')
ax1.text(0.02, 0.04, 'annotations = mean |ETFs perturbed| (model-free noise measure)',
         transform=ax1.transAxes, fontsize=7, color='grey')
plt.tight_layout()
png_path = os.path.join(OUT_DIR, 'stage3_label_noise_sweep.png')
plt.savefig(png_path, dpi=130)
print(f"Saved plot  -> {png_path}")
